# Generated by Django 2.2.6 on 2020-04-25 21:10

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True, unique=True),
        ),
    ]
