# Generated by Django 2.2.6 on 2020-05-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=500)),
                ('field', models.CharField(choices=[('Identification', 'Identification'), ('Transport', 'Transport'), ('Money', 'Money'), ('Attraction', 'Attraction')], max_length=14)),
            ],
        ),
    ]
