# Generated by Django 2.2.6 on 2020-06-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20200603_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='visited_times',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
